# Generated by Django 3.2.23 on 2023-12-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcom',
            name='gny',
        ),
    ]
